services:
  postgres:
    image: postgres:17
    container_name: medical-postgres
    environment:
      POSTGRES_DB: medical_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zed152zed
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    container_name: medical-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/medical_api
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=zed152zed
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET=mIvgVyq2OTrjbaFPSCx9YlRG7BzW4kZA
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  postgres_data: